a2a.creative-writer.url=http://localhost:8080
a2a.style-scorer.url=http://localhost:8081
# ---- Option A : Mistral AI (distant) ----
# dev.langchain4j.cdi.plugin.ollama.class=dev.langchain4j.model.mistralai.MistralAiChatModel
# dev.langchain4j.cdi.plugin.ollama.config.api-key=${MISTRAL_API_KEY}
# dev.langchain4j.cdi.plugin.ollama.config.model-name=mistral-small-latest
# dev.langchain4j.cdi.plugin.ollama.config.temperature=0.0

# ---- Option B : Ollama (local) ----
dev.langchain4j.cdi.plugin.ollama.class=dev.langchain4j.model.ollama.OllamaChatModel
dev.langchain4j.cdi.plugin.ollama.config.base-url=http://127.0.0.1:11434
dev.langchain4j.cdi.plugin.ollama.config.model-name=qwen2.5:7b
dev.langchain4j.cdi.plugin.ollama.config.temperature=0.0
dev.langchain4j.cdi.plugin.ollama.config.timeout=PT10M
dev.langchain4j.cdi.plugin.ollama.config.log-requests=true
dev.langchain4j.cdi.plugin.ollama.config.log-responses=true
