a2a.server.url=http://localhost:8080
dev.langchain4j.cdi.plugin.ollama.class=dev.langchain4j.model.ollama.OllamaChatModel
dev.langchain4j.cdi.plugin.ollama.config.base-url=http://127.0.0.1:11434
dev.langchain4j.cdi.plugin.ollama.config.model-name=qwen2.5:7b
dev.langchain4j.cdi.plugin.ollama.config.temperature=0.0
dev.langchain4j.cdi.plugin.ollama.config.timeout=PT10M
dev.langchain4j.cdi.plugin.ollama.config.log-requests=true
dev.langchain4j.cdi.plugin.ollama.config.log-responses=true
dev.langchain4j.cdi.plugin.ollama.config.supportedCapabilities=dev.langchain4j.model.chat.Capability.RESPONSE_FORMAT_JSON_SCHEMA
