# ============================================
# LangChain4j-CDI Demo 4 : Guardrails (solution)
# ============================================
# Mistral AI model configuration

dev.langchain4j.cdi.plugin.my-model.class=dev.langchain4j.model.mistralai.MistralAiChatModel
dev.langchain4j.cdi.plugin.my-model.config.api-key=${MISTRAL_API_KEY}
dev.langchain4j.cdi.plugin.my-model.config.model-name=mistral-small-latest
dev.langchain4j.cdi.plugin.my-model.config.temperature=0.9
dev.langchain4j.cdi.plugin.my-model.config.log-requests=true
dev.langchain4j.cdi.plugin.my-model.config.log-responses=true
