# ============================================
# LangChain4j-CDI Demo 1 : AI Agent (solution)
# ============================================

# Regular chat model
# ---- Option A : Mistral AI (distant) ----
dev.langchain4j.cdi.plugin.my-model.class=dev.langchain4j.model.mistralai.MistralAiChatModel
dev.langchain4j.cdi.plugin.my-model.config.api-key=${MISTRAL_API_KEY}
dev.langchain4j.cdi.plugin.my-model.config.model-name=mistral-small-latest

# ---- Option B : Ollama (local) ----
#dev.langchain4j.cdi.plugin.my-model.class=dev.langchain4j.model.ollama.OllamaChatModel
#dev.langchain4j.cdi.plugin.my-model.config.base-url=http://localhost:11434
#dev.langchain4j.cdi.plugin.my-model.config.model-name=ministral-3:3b

dev.langchain4j.cdi.plugin.my-model.config.temperature=0.9
dev.langchain4j.cdi.plugin.my-model.config.log-requests=true
dev.langchain4j.cdi.plugin.my-model.config.log-responses=true


# Streaming chat model for SSE demo
# ---- Option A : Mistral AI (distant) ----
dev.langchain4j.cdi.plugin.my-streaming-model.class=dev.langchain4j.model.mistralai.MistralAiStreamingChatModel
dev.langchain4j.cdi.plugin.my-streaming-model.config.api-key=${MISTRAL_API_KEY}
dev.langchain4j.cdi.plugin.my-streaming-model.config.model-name=mistral-small-latest

# ---- Option B : Ollama (local) ----
#dev.langchain4j.cdi.plugin.my-streaming-model.class=dev.langchain4j.model.ollama.OllamaStreamingChatModel
#dev.langchain4j.cdi.plugin.my-streaming-model.config.base-url=http://localhost:11434
#dev.langchain4j.cdi.plugin.my-streaming-model.config.model-name=ministral-3:3b

dev.langchain4j.cdi.plugin.my-streaming-model.config.temperature=0.9
dev.langchain4j.cdi.plugin.my-streaming-model.config.log-requests=true
dev.langchain4j.cdi.plugin.my-streaming-model.config.log-responses=true

# Vision model for image analysis
# IMPORTANT: This model MUST support image analysis (vision capabilities)

# ---- Option A : Mistral AI (distant) ----
dev.langchain4j.cdi.plugin.vision-model.class=dev.langchain4j.model.mistralai.MistralAiChatModel
dev.langchain4j.cdi.plugin.vision-model.config.api-key=${MISTRAL_API_KEY}
dev.langchain4j.cdi.plugin.vision-model.config.model-name=pixtral-large-latest

# ---- Option B : Ollama (local) ----
#dev.langchain4j.cdi.plugin.vision-model.class=dev.langchain4j.model.ollama.OllamaChatModel
#dev.langchain4j.cdi.plugin.vision-model.config.base-url=http://localhost:11434
#dev.langchain4j.cdi.plugin.vision-model.config.model-name=ministral-3:3b

dev.langchain4j.cdi.plugin.vision-model.config.temperature=0.3
